# https://docs.travis-ci.com/user/languages/android/
language: android
android:
  components:
    # Uncomment the lines below if you want to
    # use the latest revision of Android SDK Tools
    # - tools
    # - platform-tools

    # The BuildTools version used by your project
    - build-tools-26.0.2

    # The SDK version used to compile your project
    - android-27

    # Additional components
    - extra-google-google_play_services
    - extra-google-m2repository
    - extra-android-m2repository
    - addon-google_apis-google-26
    - extra-android-support

  # Specify at least one system image,
  # if you need to run emulator(s) during your tests
  #- sys-img-armeabi-v7a-android-26
  #- sys-img-armeabi-v7a-android-17

  # https://github.com/googlesamples/android-ndk/blob/master/.travis.yml
  # https://docs.travis-ci.com/user/customizing-the-build/#Building-Specific-Branches
branches:
  only:
  - master
  - dev
  - release
  - /^picgo_.*\.dev_.*$/
  - /^picgo_.*\.beta_.*$/
  - /^v\d+\.\d+(\.\d+)?(-\S*)?$/
before_install:
  # - rm -fr $HOME/android-ndk-r16b
  #- curl -L http://dl.google.com/android/repository/android-ndk-r16b-linux-x86_64.zip -O
  #- unzip -oq android-ndk-r16b-linux-x86_64.zip
  #- rm android-ndk-r16b-linux-x86_64.zip
  #- export ANDROID_NDK_HOME=$HOME/android-ndk-r16b
  #https://github.com/leinardi/androidthings-pio/blob/master/.travis.yml
  - mkdir -p $ANDROID_HOME/licenses
  - echo "8933bad161af4178b1185d1a37fbf41ea5269c55" > $ANDROID_HOME/licenses/android-sdk-license
  - echo "d56f5187479451eabf01fb78af6dfcb131a6481e" >> $ANDROID_HOME/licenses/android-sdk-license

install:
  - echo y | sdkmanager 'ndk-bundle'
  - echo y | sdkmanager 'cmake;3.6.4111459'
  - echo y | sdkmanager 'lldb;3.0'

before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/

cache:
  directories:
    - $HOME/.m2
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
    - $HOME/.android/build-cache

script:
  - chmod +x ./gradlew
  - ./gradlew clean assembleRelease

before_deploy:
  # Set up git user name and tag this commit
  - git config --local user.name "intret@qq.com"
  - git config --local user.email "intret@qq.com"
  # package .apk
  - bash ./.ci/ci-package-travis.sh
  - export RELEASE_PKG_FILE=$(ls ./app/build/outputs/ci-travis-apk/*.apk)
  - echo "deploying $RELEASE_PKG_FILE to GitHub releases"
  #- chmod +x ./.ci/ci-print-version.sh; APP_FILE_NAME=$(./.ci/ci-print-version.sh )
  #- echo "change tag name to $APP_FILE_NAME"
  #- git tag "$APP_FILE_NAME"
  # git tag "$(date +'%Y%m%d%H%M%S')-$(git log --format=%h -1)"

deploy:
  provider: releases
  prerelease: true
  file_glob: "true"
  file: "app/build/outputs/ci-travis-apk/*.apk"
  skip_cleanup: true
  on:
    tags: true
